// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSqFmu2zFHJhbB2JWXoNDnRUOBYbC06hU',
    appId: '1:404451208967:web:d21d038acc3db2c2f05fa2',
    messagingSenderId: '404451208967',
    projectId: 'carently-94153',
    authDomain: 'carently-94153.firebaseapp.com',
    storageBucket: 'carently-94153.appspot.com',
    measurementId: 'G-8GEQ013X55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2d45fnPurgofuw8zbHrPN3PYySuThB1Q',
    appId: '1:404451208967:android:0f282a1bbf2457d4f05fa2',
    messagingSenderId: '404451208967',
    projectId: 'carently-94153',
    storageBucket: 'carently-94153.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv_DWShLEbIh06LSkINfnVPkGD0y6Fxvc',
    appId: '1:404451208967:ios:27c1228371b2e708f05fa2',
    messagingSenderId: '404451208967',
    projectId: 'carently-94153',
    storageBucket: 'carently-94153.appspot.com',
    iosBundleId: 'com.example.carrently',
  );

}